// <auto-generated />
using Apricode.ApricodeGames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apricode.ApricodeGames.API.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220529202335_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Apricode.ApricodeGames.API.Data.Model.DevelopmentStudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("DevelopmentStudios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Take2"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Blizzard"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Konami"
                        });
                });

            modelBuilder.Entity("Apricode.ApricodeGames.API.Data.Model.GameGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Shooter"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Strategy"
                        });
                });

            modelBuilder.Entity("Apricode.ApricodeGames.API.Data.Model.GameItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DevelopmentStudioId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentStudioId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Apricode.ApricodeGames.API.Data.Model.GameItemGameGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GameItemId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameItemId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameItemGameGenres");
                });

            modelBuilder.Entity("Apricode.ApricodeGames.API.Data.Model.GameItem", b =>
                {
                    b.HasOne("Apricode.ApricodeGames.API.Data.Model.DevelopmentStudio", "DevelopmentStudio")
                        .WithMany("Games")
                        .HasForeignKey("DevelopmentStudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevelopmentStudio");
                });

            modelBuilder.Entity("Apricode.ApricodeGames.API.Data.Model.GameItemGameGenre", b =>
                {
                    b.HasOne("Apricode.ApricodeGames.API.Data.Model.GameItem", "GameItem")
                        .WithMany()
                        .HasForeignKey("GameItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apricode.ApricodeGames.API.Data.Model.GameGenre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameItem");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Apricode.ApricodeGames.API.Data.Model.DevelopmentStudio", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
